### PR TITLE
bug: fixed typo in keystone url of scs-community-platform

### PR DESCRIPTION
**Pull request by tibeer**
Kind of fatal if you have the wrong keystone url. Tried the profile today and noticed the wrong url.

Signed-off-by: Tim Beermann <beermann@osism.tech>

### CODE REVIEW

**Comment by mxmxchere** [comment]
Hi Tim, thanks for the PR. Could you please increment the chart version in the Chart.yaml. Otherwise no new release will be triggered. Thanks in advance :)

**Comment by tibeer** [comment]
> Hi Tim, thanks for the PR. Could you please increment the chart version in the Chart.yaml? Otherwise no new release will be triggered. Thanks in advance :)

Done.

**Comment by mxmxchere** [comment]
I think this is the relevant location: https://github.com/tibeer/23ke-charts/blob/977ac02d82f62e03daacc02c3497f6290cc91e26/charts/cloudprofiles/Chart.yaml#L18

**Comment by tibeer** [comment]
> I think this is the relevant location: https://github.com/tibeer/23ke-charts/blob/977ac02d82f62e03daacc02c3497f6290cc91e26/charts/cloudprofiles/Chart.yaml#L18

Done.

**Comment by mxmxchere** [comment]
very good, thanks :)

**Pull request merged**
